// Placeholders
export const PLACEHOLDER_ENTER_NAME="Enter name"
export const PLACEHOLDER_ENTER_PHONE="Enter number"
export const PLACEHOLDER_ENTER_INVITE_CODE="Enter code"
export const PLACEHOLDER_ENTER_CARD = "Enter the name of the card"
export const PLACEHOLDER_SEARCH_CONTACT = "Search for a contact"


// Button Titles
export const TITLE_LOGIN = "Log in"
export const TITLE_VERIFY = "Verify"
export const TITLE_SKIP = "Skip"
export const TITLE_VERIFYING = "Verifying"
export const TITLE_SEND = "Send"
export const TITLE_RE_SEND = "RE-SEND"
export const TITLE_RE_VERIFY = "RE-VERIFY"
export const TITLE_SIGNUP = "Sign up"
export const TITLE_HOW_IT_WORKS = "How it works"
export const TITLE_SUBMIT = "Submit"
export const TITLE_SUBMITTING = "Submitting"
export const TITLE_SAVE = "SAVE"
export const TITLE_CANCEL = "CANCEL"
export const TITLE_EDIT = "EDIT"
export const TITLE_NEXT = "NEXT"
export const TITLE_PROCEED = "PROCEED"
export const TITLE_SEARCH = "Search"
export const TITLE_NEW_REQUEST = "New Request"
export const TITLE_GOT_IT = "GOT IT"
export const TITLE_BACK = "BACK"
export const TITLE_INVITE = "INVITE"
export const PAY = "PAY"
export const YES = "YES"
export const NO = "NO"
export const COPY_CODE = "COPY CODE"
export const INVITE_WITH_CODE = "INVITE WITH CODE"
export const TITLE_CONTACT_US = "Contact us"
export const NEW = "New"
export const CREATE = "Create"

// Phone Verification 
export const SENDING_CODE = "Sending verification code."
export const CODE_SENT = "Code sent. Please enter the OTP."
export const CODE_RECEIVED = "Code obtained from SMS. Verifying..."
export const VERIFYING_CODE = "Verifying code..."
export const CODE_SENT_AUTO_VERIFY = "Code sent. Waiting to receive SMS."
export const INCORRECT_CODE_ENTERED = "Sorry, the code entered is incorrect."
export const CODE_EXPIRED = "Sorry, the code has expired. Please try resending the code."
export const PHONE_VERIFIED = "Great! Your phone number is verified."
export const LOGGING_YOU_IN = "Logging you in..."
export const PHONE_VERIFICATION_ERROR = "Verification failed. Please ensure phone number and country code are correct."
export const SEND_CODE_FAILED = "Failed to send code. Please ensure your phone number is correct."
export const PHONE_ALREADY_EXISTS = "Sorry, there is already an account with this number."
export const PHONE_DOES_NOT_EXIST = "Sorry, we could not find a user with that phone number."

// Screen Titles
export const APP_TITLE = "Circles"
export const HOME = "Home"
export const USER = "User"
export const PROFILE = "Profile"
export const SIGN_OUT = "Sign Out"
export const APPROVE = "APPROVE"
export const CONTACT_US = "Contact Us!"
export const WELCOME = "Welcome!"
export const WELCOME_BACK = "Welcome back!"
export const ENTER_INVITE_CODE = "Invite Code"
export const SEARCH_PAGE_TITLE = "Search for a card"
export const REQUEST_FOR = "Request for:"
export const TITLE_REQUEST_COMPLETED = "Great!"
export const ADD_OR_DELETE_CARDS = "Select cards you own"


// Other string
export const ABHIRAM = "Abhiram"
export const ANCHAL = "Anchal"
export const CO_FOUNDER = "Co-founder"
export const CONTACT_US_TEXT_1 = "Circles is still quite young but we're on this all day."
export const CONTACT_US_TEXT_2 = "We'd love for you to reach out to us for anything."
export const CONTACT_US_TEXT_3 = "Even if its just to say hi!"
export const ADD_TO_CIRCLE = "Add to Circle"
export const HOW_IT_WORKS = "How it works"
export const SHARE_YOUR_INVITE_CODE = "Share your invite code: "
export const FRIENDS_FIND_YOUR_CODE = "Your friends can find you using this code"
export const ENTER_FRIENDS_CODE = "Enter your friend's code"
export const LOADING_DOTS = "Loading..."
export const SEARCH_FRIENDS = "...or, search your friends"
export const MY_CIRCLE = "My Circle"
export const CARD_COLON = "Card: "
export const TO_COLON = "To: "
export const FROM_COLON = "From: "
export const AMOUNT_COLON = "Amount: "
export const REQUEST_SENT = "Request sent!"
export const SENDING = "Sending"
export const SENT = "Sent"
export const RUPEES_SHORT = "Rs. "
export const ACCEPT = "Accept"
export const DECLINE = "Decline"
export const CHAT = "Chat"
export const REQUEST_ACCESS_CARD = "Request: Access Card"
export const REQUEST_ADD_TO_CIRCLE = "Request: Add to Circle"
export const ADDED_TO_CIRCLES = "You'll be added to each other's Circles."
export const OUTSIDE_CIRCLES = "You'll remain outside each other's Circles."
export const START_ENCRYPTED_CHAT = "Start an encrypted chat with sender"
export const RESUME_ENCRYPTED_CHAT = "Resume your encrypted chat"
export const NOTIFY_SENDER = "Oops! We'll notify sender accoringly."
export const AWAITING_RESPONSE_FROM = "Awaiting response from "
export const LAST_UPDATED = "Last Updated: "
export const STATUS_COLON = "Status: "
export const DATE_COLON = "Date: "
export const NAME_COLON = "Name: "
export const PHONE_COLON = "Phone: "
export const OPEN = "Open"
export const USERS_IN_CIRCLE = "Friends in Circle: "
export const COPIED = "Copied!"
export const SPOTS_LEFT = "Spots left: "
export const LAST_UPDATED_COLON = "Updated: "
export const NUM_REQUESTS = "Number of Requests: "
export const NUM_POSTS = "Number of Posts: "
export const FIND_CARD = "Find the card"
export const ADD_FRIENDS = "Add friends"
export const POSTS_IN_CIRCLE = "Posts in Circle"
export const FIRE_AWAY = "Fire away!"
export const NEW_POST = "New Post"
export const ONLY_USERS_CIRCLE_NOTIFIED = "Only people in your Circle will be notified"
export const POST_SUBMITTED = "Post submitted!"
export const SUBMITTED = "Submitted"
export const POST = "Post"
export const ACTION_COMPLETED = "Action successfully completed."
export const SEARCH_EXPLAINER = "Find cardholders within your Circle and your friends' Circles."
export const SETTING_UP_YOUR_CHAT = "Setting up your chat..."
export const OK = "OK"
export const ABOUT_CIRCLE = "About Your Circle"
export const CIRCLE_TOOLTIP_EXPLAINER = ""
export const GREAT_WELCOME = "Great, welcome!"
export const FOUND_INVITE_CODE = "Bingo! That's a valid invite code."
export const INVITE_CODE_NOT_FOUND = "Sorry, that's not a valid code."
export const APP_INVITE_ONLY = "Hi! At this time, Circles is invite-only."
export const ENTER_OTP = "Enter OTP: "
export const NO_POSTS_TO_DISPLAY = "No posts to display."
export const NO_REQUESTS_TO_DISPLAY = "No requests to display."
export const TIP_EXPAND_CIRCLE_INCREASE_ACTIVITY = "Tip: Expand your Circle for more activity here!"
export const TIP_EXPAND_CIRCLE_INCREASE_CARDHOLDERS = "Tip: Expand your Circle to increase your chances of finding a cardholder!"
export const SEND_CIRCLE_REQUEST_CONFIRMATION = "Send % a request to add to your Circle? If accepted, you will be added to each other's Circles."
export const SECOND_DEGREE_CARDHOLDER_NAME = "%0 in %1's Circle"
export const OPTIONALLY_ENTER_OTP = "This is taking a while. If you've already received the OTP, please enter above."
export const PICK_CARDS_YOU_OWN = "Cards are ready. Pick ones you own!"

// Error
export const ENTER_VALID_NAME = "Please enter a valid name."
export const ENTER_VALID_PHONE_NUMBER = "Please enter a valid phone number."
export const ADD_VALID_IMAGE = "Please upload a photo to proceed."
export const OPERATION_IN_PROGRESS = "Verification is in progress."
export const SERVER_CONNECTION_ERROR = "Sorry, there seems to be a problem reaching our servers."
export const ERROR_FINDING_CIRCLE_USERS = "Sorry, there was a problem getting users in your Circle."
export const ERROR_SENDING_FRIEND_REQUEST = "Sorry, there was an error sending your friend request."
export const ERROR_SEARCHING_CARDHOLDERS = "Sorry, there was a problem finding cardholders."
export const SESSION_EXPIRED = "Your session has expired. Please log out and log back in again."
export const GENERIC_ERROR = "Sorry, something went wrong. Please try again."
export const ENTER_VALID_AMOUNT = "Please enter a valid purchase amount"
export const ENTER_VALID_TEXT = "Please enter valid text to submit"
export const ENTER_SEARCH_INPUT = "Please enter a valid search input"
export const CANNOT_GET_CARDS = "Sorry, we're unable to get the cards at the moment."
export const FAILED_TO_CREATE_CHAT = "Sorry, we're unable to set up your chat. Please try again later."
export const NO_CARDS_ON_PROFILE = "No cards added to Profile"
export const ENTER_VALID_CODE = "Please enter a valid code"
export const THAT_IS_YOUR_CODE = "Looks like you entered your own code!"
export const COULD_NOT_CONNECT_SERVER = "Oops! Looks like your internet connection is poor."
export const NO_USERS_FOUND_ID = "Sorry, no user found with that code"
export const NO_VALID_USER_FRIEND_REQUEST = "Sorry, no valid user found to send request to."
export const FRIEND_REQUEST_ALREADY_SENT = "Oh, oh. An identical request already exists. Please head over to the Requests page to manage your connections." // TODO
export const TOO_MANY_IN_CIRCLE = "Sorry, your Circle is full. We restrict the number of people in a Circle to %"

// Friend requests
export const ACCEPTED = "Accepted"
export const ACCEPTING = "Accepting"
export const DECLINED = "Declined"
export const PENDING = "Pending"
export const IN_YOUR_CIRCLE = "In your Circle: "
export const IN_YOUR_FRIENDS_CIRCLE = "In your friends' Circles: "
export const REQUEST = "Request"
export const CALL = "Call"
export const ADD = "Add"
export const ADD_SUBTITLE = "Search for and add people to your Circle."
export const CONNECTIONS = "Connections"
export const FRIEND_REQUESTS_SUBTITLE = "Manage connections within your Circle"
export const BROADCAST = "Broadcasts"
export const BROADCAST_SUBTITLE = "Send or view short messages within your Circle."
export const FRIEND_REQUEST_ACCEPTED_BODY_FIRST = "Yay! {} has accepted your request to add to Circle."
export const FRIEND_REQUEST_ACCEPTED_BODY_SECOND = "You have been added to each other's Circles!"
export const FRIEND_REQUEST_DECLINED_BODY_FIRST = "Oops! Looks like {} has declined your request to add to Circle."
export const FRIEND_REQUEST_DECLINED_BODY_SECOND = "If you think this could be by mistake, share your Circles code with him."
export const LIMIT_REACHED_CIRCLE = "Your Circle is full. Well done!"
export const ADD_TO_CIRCLE_REQUESTS = "Add to Circle Requests"

// Access Requests
export const ACCESS_REQUEST_ACCEPTED_BODY_FIRST = "Yay! {} has accepted your request to access their card."
export const ACCESS_REQUEST_ACCEPTED_BODY_SECOND = "Head over to the encrypted chat!"
export const ACCESS_REQUEST_DECLINED_BODY_FIRST = "Oops! Looks like {} has declined your request to access their card."
export const ACCESS_CARD_REQUESTS = "Access Card"
export const ACCESS_CARD_REQUESTS_SUBTITLE = "Manage requests for card access"
export const NEW_CHAT_MESSAGE_TITLE = "New message from "
export const NEW_CHAT_MESSAGE_BODY = "You have new messges in your encrypted chat"

// Cards screen
export const TITLE_CARDS_SCREEN = "One Last Thing"
export const SUBTITLE_CARDS_SCREEN = "Tell your Circle what cards you own."
export const CARDS_ADDED_PREFIX = "You've added "
export const CARDS_ADDED_SUFFIX = " card(s):"
export const CARDS_COLON = "Cards: "

// Templates
export const WHATSAPP_SHARE_CODE = "https://wa.me/?text=Use my invite code: % to sign up for Circles or to add me in your Circle."
export const NUM_FRIENDS_CAN_ADD_TO_CIRCLE = "You can add % more friend(s) to your Circle"